#!/bin/bash

err () {
    local msg
    msg="${1}"
    printf 'Error: %s\n' "${msg}" >&2
}

source "../../tools.conf" >/dev/null 2>&1 || \
    { err "Could not import tool versions"; exit 1; }


MODELSIM="$(readlink -f ./modelsim.ini)"
export MODELSIM

vsim -c \
    -voptargs=+acc \
    -GDEVICE="7SERIES" \
    -GBASE_OFFSET=32\'h80000000 \
    -GBASE_OFFSET_MASK=32\'h00000FFF \
    -GRX_ENABLE='true' \
    -GTX_ENABLE='true' \
    +LOG_LEVEL=INFO \
    -do 'log -r \*; run -all; exit' -Ldir ../rundir work.top

