#!/bin/bash

err () {
    local msg
    msg="${1}"
    printf 'Error: %s\n' "${msg}" >&2
}

source "../../tools.conf" >/dev/null 2>&1 || \
    { err "Could not import tool versions"; exit 1; }


MODELSIM="$(readlink -f ./modelsim.ini)"
export MODELSIM

vsim -c -voptargs=+acc -do 'log -r \*; run -all; exit' -Ldir ../rundir work.top

