#!/bin/bash

if [[ -z "${1}" ]]; then
    printf 'Usage: %s\n' "${0} <drl_name>"
    exit 1
fi

drl_name="${1}"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    printf 'Error: Not inside a Git repository\n' >&2
    exit 1
fi

drl_root="$(git rev-parse --show-toplevel)"

if [[ -d "${drl_root}/${drl_name}" ]]; then
    printf 'Error: DRL member already exists with that name\n' >&2
    exit 1
fi

